// File auto-generated by `flutterfire configure`
// This file will be overwritten after running flutterfire configure
// Do NOT edit this file manually after Firebase setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    if (defaultTargetPlatform == TargetPlatform.windows) {
      return windows;
    }
    if (defaultTargetPlatform == TargetPlatform.linux) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for linux - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // ⚠️ NOTE: Sau khi chạy `flutterfire configure`, file này sẽ được cập nhật tự động
  // với Firebase project credentials của bạn. Không cần chỉnh sửa bây giờ.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_PLACEHOLDER_ANDROID',
    appId: '1:PLACEHOLDER:android:PLACEHOLDER',
    messagingSenderId: 'PLACEHOLDER',
    projectId: 'expense-tracker-PLACEHOLDER',
    databaseURL: 'https://expense-tracker-PLACEHOLDER.firebaseio.com',
    storageBucket: 'expense-tracker-PLACEHOLDER.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_PLACEHOLDER_IOS',
    appId: '1:PLACEHOLDER:ios:PLACEHOLDER',
    messagingSenderId: 'PLACEHOLDER',
    projectId: 'expense-tracker-PLACEHOLDER',
    databaseURL: 'https://expense-tracker-PLACEHOLDER.firebaseio.com',
    storageBucket: 'expense-tracker-PLACEHOLDER.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_PLACEHOLDER_WINDOWS',
    appId: '1:PLACEHOLDER:windows:PLACEHOLDER',
    messagingSenderId: 'PLACEHOLDER',
    projectId: 'expense-tracker-PLACEHOLDER',
    storageBucket: 'expense-tracker-PLACEHOLDER.firebasestorage.app',
  );
}
