// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnKnrX80cgCwVXMqAt6t04UkjvqRk_KWM',
    appId: '1:94959330554:web:fa731370d99d7099d11543',
    messagingSenderId: '94959330554',
    projectId: 'expenses-tracker-accounts',
    authDomain: 'expenses-tracker-accounts.firebaseapp.com',
    storageBucket: 'expenses-tracker-accounts.firebasestorage.app',
    measurementId: 'G-EK33J665QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMKnwvr_H4ZpIHs1uSFAmmtlv3Q7S-hlk',
    appId: '1:94959330554:android:fa1ce25bec9eeba0d11543',
    messagingSenderId: '94959330554',
    projectId: 'expenses-tracker-accounts',
    storageBucket: 'expenses-tracker-accounts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACN94W-0adKD7mRl_mQjOwHgi7lvz8ky8',
    appId: '1:94959330554:ios:27ab2888b519623bd11543',
    messagingSenderId: '94959330554',
    projectId: 'expenses-tracker-accounts',
    storageBucket: 'expenses-tracker-accounts.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnKnrX80cgCwVXMqAt6t04UkjvqRk_KWM',
    appId: '1:94959330554:web:87d54a833964c43dd11543',
    messagingSenderId: '94959330554',
    projectId: 'expenses-tracker-accounts',
    authDomain: 'expenses-tracker-accounts.firebaseapp.com',
    storageBucket: 'expenses-tracker-accounts.firebasestorage.app',
    measurementId: 'G-Z561R23C4Y',
  );
}
